### ISSUE TITLE
Broken dependency 

### ISSUE THREAD

**Issue by igoose1** [cp-tools/cpt#16]
## Bug description
github.com/go-rod/rod v0.92.0 in go.mod is broken.

## Steps to reproduce
1. clone cpt repository
2. go build
3. see an error

## Expected Behaviour
I expect correctly built cpt.

## Error messages/Screenshots (optional)
I got

```
../../../../pkg/mod/github.com/ysmood/leakless@v0.6.12/leakless.go:106:47: undefined: leaklessBin
```

## System Details
 - OS: FreeBSD 12.2-RELEASE
 - Version: master (commit: e51706852f4e97ae433fd23b97b1eb3752230ab1) and v0.16.2 both.

## Any suggestions?
Update github.com/go-rod/rod to v0.97.12 in cpt and cpt-lib. Also, just to check, I tried to fix leakless.go myself: rename leaklessBin to bin did a job and allowed to build your package. But that's not an option. That's an another dependency hell!

**Comment by infalmo** [comment]
Thanks for the report. I'm somewhat busy until the end of this month, so I won't be able to work on this project till then.
Maybe you could help me by making a PR to fix the issue?

**Comment by igoose1** [comment]
> Thanks for the report.

Hey :-)  Glad you answered so fast.

> I'm somewhat busy until the end of this month, so I won't be able to
> work on this project till then. Maybe you could help me by making a PR
> to fix the issue?

Yes, I think I could. My plan was to create an issue before just to let
you know something is broken and then look deeper to create a PR. Wait
for it!

-- 
Oskar Sharipov
gpg fingerprint: BAC3 F049 748A D098 A144  BA89 0DC4 EA75 714C 75B5
