### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by pgimalac** [cp-tools/cpt#18]
Hi, I saw that the only supported browsers were google chrome / chromium and microsoft edge, but as I use firefox I'm interested in knowing why it isn't supported, and eventually ask for it to be supported if you think it can be done.

Is it because you just never tried, would it necessitate specific code to be handled, or does firefox miss a feature to be usable with your tool ?

I tried setting firefox as my browser (without touching the code), at first I got errors with headless mode, which needed me to close my opened firefox (which isn't very convenient but hopefully there is a way around...) and after closing it I got this error message, that I didn't try to solve (yet):
`error launching automated browser: {0 this.browsingContext is null get title@chrome://remote/content/cdp/targets/TabTarget.jsm:108:5`

If you have any advice to give me about that I'd be glad to hear it !

**Comment by pgimalac** [comment]
I just noticed it was mentioned explicitly that firefox wasn't supported in https://github.com/cp-tools/cpt/pull/9, so I guess you tried...

**Comment by infalmo** [comment]
See: https://github.com/cp-tools/cpt-lib#which-browsers-are-supported

**Comment by pgimalac** [comment]
Oh okay I see, I guess it's not up to you then... Too bad for me !
